Language:
  items:
    title: "Mention options"

    groups:
      languages:
        title: "Language options"
        desc: "Default language options."
      posts:
        title: "Topics and messages"
        desc: "You can use this option to change some settings in the subject or messages."
      recaptcha:
        title: "ReCaptcha settings"
        desc: "ReCaptcha key and secret key are entered from this setting."
      site:
        title: "General settings"
        desc: "The general settings of the website include options such as website title and description."
      styles:
        title: "Style settings"
        desc: "A set of options where you can manage the site logo or emojis."
      users:
        title: "User settings"
        desc: "Options such as user settings or profile photo."

    forms:
      site:
        site_url:
          name: "Site address"
          desc: "The full address of your site. It must not end with '/'."
        site_title:
          name: "Site Title"
          desc: "The title of your site. This will appear on all pages."
        site_short_title:
          name: "Short title"
          desc: "The short title of your site."
        meta_description:
          name: "Meta description"
          desc: "Meta description. It is important for SEO, make sure it is between 50-160 characters."
        site_mail:
          name: "Contact e-mail address"
          desc: "It is the main e-mail address of your site to be used for communication. Regardless of which mail you use for outgoing mail, it will be forwarded under this name."

      languages:
        default_language:
          name: "Default language"
          desc: "Please select your site's default language. If your language option does not appear in the options, you can install or create a new package from the <strong>Languages</strong> tab."

      posts:
        per_page:
          name: "The amount of messages per page."
          desc: "Maximum posts per page, specific to topics and homepage."
        title_char_min:
          name: "Minimum topic length"
          desc: "Specifies the minimum title length that can be written when opening a topic."
        content_char_min:
          name: "Minimum content length"
          desc: "Minimum content length when opening a topic."
        max_attachments:
          name: "Maximum number of files that can be added."
          desc: "Maximum limit of files that can be attached to a message."
        attachment_max_size:
          name: "Maximum file size that can be attached."
          desc: "The maximum file size to attach to the message."

      recaptcha:
        recaptcha_using:
          name: "ReCaptcha API"
          desc: "The ReCaptcha API you want to use. Or turn off captcha."
        recaptcha_none: "I don't want to use captcha."
        gr_secret_key:
          name: "secret key"
          desc: "ReCaptcha secret key."
        gr_site_key:
          name: "Site key"
          desc: "ReCaptcha site key."

      styles:
        site_logo:
          name: "Site logo"
          desc: "Logo on top left and when registering/logging in. <br /> <strong>Maximum size: {phrase:getGlobals().admin.max_site_logo_size}</strong>"
        site_logo_night:
          name: "Dark mode logo"
          desc: "There should be a dark mode logo next to the normal logo. <br /> <strong>Maximum size: {phrase:getGlobals().admin.max_site_logo_size}</strong>"
        emoticon_database:
          name: "Emoji database"
          desc: "Emoji database can pull from your server or remote server. <br /> <strong>local: local server <br /> twemoji: remote server</strong>"
        default_theme:
          name: "Default theme"
          desc: "You can choose your site's default theme here."

      users:
        profile_photo_max_size:
          name: "Maximum profile photo size"
          desc: "Maximum profile photo file size that users can upload."
