name: 🚀 Feature Request
description: New features and improvements
body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: A clear description of the new feature
      validations:
          required: true
    - type: textarea
      id: example
      attributes:
          label: Example
          description: |
              A simple example of the new feature in action (include PHP code, CSS, JS etc.)
              If the new feature changes an existing feature, include a simple before/after comparison.
